import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Card } from '../components/Card';
import { Button } from '../components/Button';
import { MessageSquareHeart, Sparkles, Share2, Download } from 'lucide-react';
import { downloadAsImage, shareAsImage } from '../utils/downloadImage';

export function AIAdvice() {
  const [names, setNames] = useState('');
  const [topic, setTopic] = useState('');
  const [advice, setAdvice] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const getAdvice = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!names || !topic) return;

    setIsLoading(true);
    setAdvice('');

    try {
      const response = await fetch('/api/ai/advice', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ names, topic }),
      });

      if (!response.ok) {
        throw new Error('Failed to fetch advice');
      }

      const data = await response.json();
      setAdvice(data.advice);
    } catch (error) {
      console.error(error);
      setAdvice("Oops! The love guru is currently taking a nap. Try again later! 😴");
    } finally {
      setIsLoading(false);
    }
  };

  const handleShare = async () => {
    const text = `Love Advice for ${names} about ${topic}: "${advice}" Get yours at HeartSpark!`;
    await shareAsImage('advice-result', 'AI Love Advice', text);
  };

  const handleDownload = () => {
    downloadAsImage('advice-result', 'love-advice');
  };

  return (
    <div className="max-w-2xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white flex items-center justify-center gap-2">
          AI Love Advice <MessageSquareHeart className="w-8 h-8 text-indigo-500" />
        </h1>
        <p className="text-lg text-slate-600 dark:text-slate-400">
          Get cute, playful advice generated by our AI love guru.
        </p>
      </div>

      <Card>
        <form onSubmit={getAdvice} className="space-y-6">
          <div className="space-y-4">
            <div className="space-y-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Who is this for?</label>
              <input
                type="text"
                value={names}
                onChange={(e) => setNames(e.target.value)}
                className="w-full h-12 px-4 rounded-xl border-2 border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-slate-900 dark:text-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 dark:focus:ring-indigo-900 outline-none transition-all"
                placeholder="e.g. Me and Alex"
                required
              />
            </div>

            <div className="space-y-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">What do you need advice on?</label>
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                className="w-full h-12 px-4 rounded-xl border-2 border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-slate-900 dark:text-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 dark:focus:ring-indigo-900 outline-none transition-all"
                placeholder="e.g. How to ask them out, First date ideas"
                required
              />
            </div>
          </div>

          <Button 
            type="submit" 
            className="w-full h-14 text-lg"
            isLoading={isLoading}
            disabled={!names || !topic}
          >
            <Sparkles className="w-5 h-5 mr-2" /> Ask the Guru
          </Button>
        </form>
      </Card>

      <AnimatePresence>
        {advice && !isLoading && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: -20 }}
          >
            <Card id="advice-result" className="text-center space-y-6 bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-zinc-900 dark:to-zinc-900 border-indigo-200 dark:border-zinc-800">
              <div className="inline-block p-4 rounded-full bg-indigo-100 dark:bg-indigo-900/30 mb-2">
                <Sparkles className="w-8 h-8 text-indigo-500" />
              </div>
              
              <p className="text-xl md:text-2xl font-medium text-slate-800 dark:text-slate-200 italic font-serif leading-relaxed">
                "{advice}"
              </p>

              <div className="flex flex-wrap justify-center gap-4 pt-4" data-html2canvas-ignore>
                <Button onClick={handleShare}>
                  <Share2 className="w-4 h-4 mr-2" /> Share Advice
                </Button>
                <Button variant="outline" onClick={handleDownload}>
                  <Download className="w-4 h-4 mr-2" /> Download
                </Button>
              </div>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
