import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Card } from '../components/Card';
import { Button } from '../components/Button';
import { BookOpen, RefreshCw, Share2, Download, Sparkles, Loader2, Heart } from 'lucide-react';
import { downloadAsImage, shareAsImage } from '../utils/downloadImage';
import { generateContentWithFallback } from '../utils/ai';
import Markdown from 'react-markdown';

export function CoupleStory() {
  const [name1, setName1] = useState('');
  const [name2, setName2] = useState('');
  const [theme, setTheme] = useState('romantic');
  const [story, setStory] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name1 || !name2) return;

    setIsGenerating(true);
    setStory('');

    try {
      const prompt = `
        You are Heart Spark, an expert romance novelist.
        Write a short, engaging, and ${theme} story about two people named ${name1} and ${name2}.
        
        Please format the response in markdown with these sections:
        
        ### The Story
        (Write a 2-3 paragraph story here. Make it fun and memorable.)
        
        ### Fun Scores
        * **Romance IQ**: (Score from 0-100%)
        * **Charm Score**: (Score from 0-100%)
        * **Destiny Meter**: (Score from 0-100%)
        
        ### Heart Spark's Tip
        (Give one cute piece of relationship advice based on the story theme)
      `;

      const response = await generateContentWithFallback({
        model: 'gemini-3-flash-preview',
        contents: prompt,
      });

      setStory(response.text || 'Oops! Heart Spark got distracted by a butterfly. Try again!');
    } catch (error) {
      console.error('Error generating story:', error);
      setStory('Oops! Heart Spark is taking a break. Please check your API key or try again later.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleShare = async () => {
    const text = `Read the ${theme} story of ${name1} and ${name2} generated by Heart Spark!`;
    await shareAsImage('story-result', 'Couple Story', text);
  };

  const handleDownload = () => {
    downloadAsImage('story-result', 'couple-story');
  };

  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-pink-600 to-purple-600 dark:from-pink-400 dark:to-purple-400 flex items-center justify-center gap-2">
          Couple Story Generator <BookOpen className="w-8 h-8 text-pink-500 animate-pulse" />
        </h1>
        <p className="text-lg text-zinc-600 dark:text-zinc-400">
          Let Heart Spark write a personalized, fun story starring you and your crush.
        </p>
      </div>

      <Card className="bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl border-pink-100 dark:border-pink-900/30">
        <form onSubmit={handleGenerate} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">Your Name</label>
              <input
                type="text"
                value={name1}
                onChange={(e) => setName1(e.target.value)}
                className="w-full h-12 px-4 rounded-xl border-2 border-pink-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white focus:border-pink-500 focus:ring-2 focus:ring-pink-200 dark:focus:ring-pink-900 outline-none transition-all"
                required
              />
            </div>
            <div className="space-y-2">
              <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">Crush's Name</label>
              <input
                type="text"
                value={name2}
                onChange={(e) => setName2(e.target.value)}
                className="w-full h-12 px-4 rounded-xl border-2 border-pink-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white focus:border-pink-500 focus:ring-2 focus:ring-pink-200 dark:focus:ring-pink-900 outline-none transition-all"
                required
              />
            </div>
          </div>
          
          <div className="space-y-2">
            <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">Story Vibe</label>
            <select
              value={theme}
              onChange={(e) => setTheme(e.target.value)}
              className="w-full h-12 px-4 rounded-xl border-2 border-pink-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white focus:border-pink-500 focus:ring-2 focus:ring-pink-200 dark:focus:ring-pink-900 outline-none transition-all appearance-none"
            >
              <option value="romantic">Romantic & Sweet</option>
              <option value="funny">Funny & Awkward</option>
              <option value="dramatic">Dramatic & Intense</option>
              <option value="sci-fi">Sci-Fi Adventure</option>
              <option value="fantasy">Magical Fantasy</option>
            </select>
          </div>

          <Button 
            type="submit" 
            className="w-full h-14 text-lg bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600 text-white border-none shadow-[0_0_15px_rgba(236,72,153,0.4)] hover:shadow-[0_0_25px_rgba(236,72,153,0.6)] transition-all flex items-center justify-center gap-2"
            disabled={isGenerating || !name1 || !name2}
          >
            {isGenerating ? (
              <>💬 Generating romantic story... <Loader2 className="w-5 h-5 animate-spin" /></>
            ) : (
              <>Create Our Love Story ❤️ <Sparkles className="w-5 h-5" /></>
            )}
          </Button>
        </form>
      </Card>

      <AnimatePresence>
        {story && !isGenerating && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: -20 }}
          >
            <Card id="story-result" className="space-y-6 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl border-pink-100 dark:border-pink-900/30 p-8">
              <div className="flex items-center gap-3 mb-6 pb-4 border-b border-pink-100 dark:border-pink-900/30">
                <div className="w-10 h-10 rounded-full bg-pink-100 dark:bg-pink-900/30 flex items-center justify-center">
                  <Heart className="w-5 h-5 text-pink-500" />
                </div>
                <h2 className="text-2xl font-bold text-zinc-800 dark:text-white">
                  A Tale of {name1} & {name2}
                </h2>
              </div>
              
              <div className="prose dark:prose-invert max-w-none">
                <div className="text-zinc-700 dark:text-zinc-300 leading-relaxed markdown-body">
                  <Markdown>{story}</Markdown>
                </div>
              </div>

              <div className="flex flex-wrap gap-4 pt-6 border-t border-pink-100 dark:border-pink-900/30" data-html2canvas-ignore>
                <Button variant="outline" onClick={() => setStory('')} className="border-pink-200 text-pink-600 hover:bg-pink-50 dark:border-pink-800 dark:text-pink-400 dark:hover:bg-pink-900/30">
                  <RefreshCw className="w-4 h-4 mr-2" /> New Story
                </Button>
                <Button onClick={handleShare} className="bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600 text-white border-none">
                  <Share2 className="w-4 h-4 mr-2" /> Share Story
                </Button>
                <Button variant="outline" onClick={handleDownload} className="border-pink-200 text-pink-600 hover:bg-pink-50 dark:border-pink-800 dark:text-pink-400 dark:hover:bg-pink-900/30">
                  <Download className="w-4 h-4 mr-2" /> Download
                </Button>
              </div>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
