import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Card } from '../components/Card';
import { Button } from '../components/Button';
import { BookOpen, RefreshCw, Share2, Download, Sparkles, Loader2, Heart } from 'lucide-react';
import { downloadAsImage, shareAsImage } from '../utils/downloadImage';
import { generateContentWithFallback } from '../utils/ai';
import Markdown from 'react-markdown';

export function CoupleStory() {
  const [name1, setName1] = useState('');
  const [name2, setName2] = useState('');
  const [theme, setTheme] = useState('romantic');
  const [story, setStory] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name1 || !name2) return;

    setIsGenerating(true);
    setStory('');

    try {
      const prompt = `
        You are Heart Spark, an expert romance novelist.
        Write a very short, engaging, and ${theme} story about two people named ${name1} and ${name2}.
        
        CRITICAL: The story MUST be exactly 2-4 lines long. Keep it punchy and perfect for sharing on social media.
        
        Please format the response in markdown with these sections:
        
        ### The Story
        (Write the 2-4 line story here.)
        
        ### Heart Spark's Tip
        (Give one cute piece of relationship advice based on the story theme)
      `;

      const response = await generateContentWithFallback({
        model: 'gemini-3-flash-preview',
        contents: prompt,
      });

      setStory(response.text || 'Oops! Heart Spark got distracted by a butterfly. Try again!');
    } catch (error) {
      console.error('Error generating story:', error);
      setStory('Oops! Heart Spark is taking a break. Please check your API key or try again later.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleShare = async () => {
    const text = `Read the ${theme} story of ${name1} and ${name2} generated by Heart Spark!`;
    await shareAsImage('story-result', 'Couple Story', text);
  };

  const handleDownload = () => {
    downloadAsImage('story-result', 'couple-story');
  };

  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-pink-600 to-purple-600 dark:from-pink-400 dark:to-purple-400 flex items-center justify-center gap-2">
          Couple Story Generator <BookOpen className="w-8 h-8 text-pink-500 animate-pulse" />
        </h1>
        <p className="text-lg text-zinc-600 dark:text-zinc-400">
          Let Heart Spark write a personalized, fun story starring you and your crush.
        </p>
      </div>

      <Card className="bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl border-pink-100 dark:border-pink-900/30">
        <form onSubmit={handleGenerate} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">Your Name</label>
              <input
                type="text"
                value={name1}
                onChange={(e) => setName1(e.target.value)}
                className="w-full h-12 px-4 rounded-xl border-2 border-pink-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white focus:border-pink-500 focus:ring-2 focus:ring-pink-200 dark:focus:ring-pink-900 outline-none transition-all"
                required
              />
            </div>
            <div className="space-y-2">
              <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">Crush's Name</label>
              <input
                type="text"
                value={name2}
                onChange={(e) => setName2(e.target.value)}
                className="w-full h-12 px-4 rounded-xl border-2 border-pink-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white focus:border-pink-500 focus:ring-2 focus:ring-pink-200 dark:focus:ring-pink-900 outline-none transition-all"
                required
              />
            </div>
          </div>
          
          <div className="space-y-2">
            <label className="block text-sm font-medium text-zinc-700 dark:text-zinc-300">Story Vibe</label>
            <select
              value={theme}
              onChange={(e) => setTheme(e.target.value)}
              className="w-full h-12 px-4 rounded-xl border-2 border-pink-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white focus:border-pink-500 focus:ring-2 focus:ring-pink-200 dark:focus:ring-pink-900 outline-none transition-all appearance-none"
            >
              <option value="romantic">Romantic & Sweet</option>
              <option value="funny">Funny & Awkward</option>
              <option value="dramatic">Dramatic & Intense</option>
              <option value="sci-fi">Sci-Fi Adventure</option>
              <option value="fantasy">Magical Fantasy</option>
            </select>
          </div>

          <Button 
            type="submit" 
            variant="custom"
            className="w-full h-14 text-lg bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600 text-white border-none shadow-[0_0_15px_rgba(236,72,153,0.4)] hover:shadow-[0_0_25px_rgba(236,72,153,0.6)] transition-all flex items-center justify-center gap-2"
            disabled={isGenerating || !name1 || !name2}
          >
            {isGenerating ? (
              <>💬 Generating romantic story... <Loader2 className="w-5 h-5 animate-spin" /></>
            ) : (
              <>Create Our Love Story ❤️ <Sparkles className="w-5 h-5" /></>
            )}
          </Button>
        </form>
      </Card>

      <AnimatePresence>
        {story && !isGenerating && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: -20 }}
            className="flex flex-col items-center space-y-8 pb-20"
          >
            {/* ✨ THE CARD (Optimized for Capture) */}
            <div 
              id="story-result" 
              className="relative overflow-hidden rounded-[2.5rem] bg-zinc-950 border border-white/5 shadow-2xl w-full max-w-md min-h-[500px] flex flex-col"
            >
              {/* 🌈 Capture-Safe Background */}
              <div className="absolute inset-0 bg-gradient-to-br from-[#121212] via-[#0a0a0a] to-[#121212]" />
              <div className="absolute top-[-10%] right-[-10%] w-64 h-64 bg-pink-500/10 blur-[80px]" />
              <div className="absolute bottom-[-10%] left-[-10%] w-64 h-64 bg-purple-600/10 blur-[80px]" />
              
              <div className="relative z-10 p-8 h-full flex flex-col items-center justify-between text-center">
                {/* Top Header */}
                <div className="space-y-6 w-full flex flex-col items-center">
                  <div className="px-4 py-1 rounded-full bg-white/5 border border-white/10 text-[9px] uppercase font-black tracking-[0.2em] text-pink-400">
                    HeartSpark Story
                  </div>
                  
                  <div className="space-y-1">
                    <h2 className="text-3xl font-black text-white tracking-tighter italic leading-tight break-words px-2 uppercase">
                      {name1} <span className="text-pink-500 font-serif not-italic">&</span> {name2}
                    </h2>
                    <p className="text-zinc-500 text-[10px] font-bold uppercase tracking-widest">A {theme} Tale</p>
                  </div>
                </div>

                {/* Story Content */}
                <div className="w-full flex-grow flex items-center justify-center px-2">
                  <div className="prose prose-invert max-w-none">
                    <div className="text-pink-50 text-base font-medium italic leading-relaxed markdown-body">
                      <Markdown>{story}</Markdown>
                    </div>
                  </div>
                </div>

                {/* Footer */}
                <div className="w-full mt-4">
                  <p className="text-[10px] text-zinc-600 font-black uppercase tracking-[0.5em] pb-2">
                    heartspark.app
                  </p>
                </div>
              </div>
            </div>

            {/* 🕹️ ACTION DOCK */}
            <div className="flex items-center justify-center gap-3 w-full max-w-[380px] px-2">
              <Button 
                onClick={handleShare} 
                className="flex-[2] rounded-full bg-pink-600 hover:bg-pink-500 text-white font-bold h-12 shadow-lg shadow-pink-500/20 transition-all active:scale-95 flex items-center justify-center border-none"
              >
                <Share2 className="w-4 h-4 mr-2" /> Share
              </Button>
              
              <Button 
                onClick={handleDownload} 
                className="flex-[2] rounded-full bg-zinc-900/80 hover:bg-zinc-800 text-white font-bold h-12 backdrop-blur-xl border border-pink-500/40 shadow-xl transition-all active:scale-95 flex items-center justify-center group"
              >
                <Download className="w-4 h-4 mr-2 text-pink-500 group-hover:animate-bounce" /> 
                <span>Save</span>
              </Button>

              <button 
                onClick={() => setStory('')} 
                className="w-12 h-12 rounded-full bg-zinc-900 border border-zinc-700 hover:border-pink-500/50 hover:bg-zinc-800 text-zinc-300 hover:text-pink-400 flex items-center justify-center transition-all active:scale-90 group shadow-2xl"
                title="New Story"
              >
                <RefreshCw className="w-5 h-5 group-hover:rotate-180 transition-transform duration-500" />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
