import React from 'react';
import { motion } from 'motion/react';
import { FileText, AlertTriangle, Users, Scale } from 'lucide-react';

export function TermsOfService() {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="text-center mb-16">
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ type: "spring", duration: 0.8 }}
          className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-pink-100 dark:bg-pink-500/10 text-pink-600 dark:text-pink-400 mb-6"
        >
          <FileText className="w-10 h-10" />
        </motion.div>
        <h1 className="text-5xl md:text-6xl font-bold text-zinc-900 dark:text-white mb-6 tracking-tight">
          Terms of <span className="text-transparent bg-clip-text bg-gradient-to-r from-pink-600 to-purple-600 dark:from-pink-400 dark:to-purple-400">Service</span>
        </h1>
        <p className="text-xl text-zinc-600 dark:text-zinc-400 max-w-2xl mx-auto">
          The rules of the game. Please read these carefully before using HeartSpark.
        </p>
        <p className="text-sm text-zinc-500 dark:text-zinc-500 mt-4">
          Last updated: {new Date().toLocaleDateString()}
        </p>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl rounded-3xl shadow-xl border border-pink-100/50 dark:border-pink-900/30 p-8 md:p-12 relative overflow-hidden"
      >
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-pink-500 via-purple-500 to-rose-500"></div>
        
        <div className="space-y-10 text-zinc-700 dark:text-zinc-300 leading-relaxed">
          <section className="relative">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 rounded-xl bg-pink-50 dark:bg-pink-500/10 text-pink-600 dark:text-pink-400">
                <Scale className="w-6 h-6" />
              </div>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-white">1. Acceptance of Terms</h2>
            </div>
            <p className="mb-4 text-lg">
              By accessing and using HeartSpark ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the Service.
            </p>
          </section>

          <section className="relative">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 rounded-xl bg-rose-50 dark:bg-rose-500/10 text-rose-600 dark:text-rose-400">
                <AlertTriangle className="w-6 h-6" />
              </div>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-white">2. Disclaimer of Professional Advice</h2>
            </div>
            <div className="bg-rose-50 dark:bg-rose-500/10 p-6 rounded-2xl border border-rose-100 dark:border-rose-700/50 mb-4">
              <p className="text-rose-900 dark:text-rose-200 font-medium">
                <strong>HeartSpark is an AI-powered entertainment and self-reflection tool.</strong> The advice, analysis, and suggestions provided by LoveGPT, Astrology AI, and other tools on this platform are generated by artificial intelligence and are for entertainment purposes only.
              </p>
            </div>
            <p className="text-lg">
              Our Service does not provide professional psychological, relationship, legal, or medical advice. Always consult with a qualified professional for serious relationship or mental health concerns.
            </p>
          </section>

          <section className="relative">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 rounded-xl bg-purple-50 dark:bg-purple-500/10 text-purple-600 dark:text-purple-400">
                <Users className="w-6 h-6" />
              </div>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-white">3. User-Generated Content</h2>
            </div>
            <p className="mb-4 text-lg">
              When posting to the Community Stories board or interacting with other users, you agree not to:
            </p>
            <ul className="list-disc pl-6 space-y-3 text-lg">
              <li>Post content that is illegal, abusive, harassing, or discriminatory.</li>
              <li>Share personally identifiable information (PII) of yourself or others without consent.</li>
              <li>Post spam, promotional material, or malicious links.</li>
            </ul>
            <p className="mt-6 text-lg">
              We reserve the right to moderate, remove, or edit any content that violates these terms, and to suspend or terminate accounts that repeatedly violate our community guidelines.
            </p>
          </section>

          <section className="relative">
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-white mb-4">4. Intellectual Property</h2>
            <p className="text-lg">
              The Service and its original content (excluding user-generated content), features, and functionality are and will remain the exclusive property of HeartSpark and its licensors. The Service is protected by copyright, trademark, and other laws.
            </p>
          </section>

          <section className="relative">
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-white mb-4">5. Limitation of Liability</h2>
            <p className="text-lg">
              In no event shall HeartSpark, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </section>

          <section className="relative">
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-white mb-4">6. Changes to Terms</h2>
            <p className="text-lg">
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </section>
        </div>
      </motion.div>
    </div>
  );
}
