import { Logo } from '../components/Logo';
import { motion } from 'motion/react';
import { Card } from '../components/Card';
import { Link } from 'react-router-dom';
import { Star, Wand2, BookOpen, Flame, MessageSquareHeart, Brain, Bot, Sparkles } from 'lucide-react';

export function Tools() {
  const tools = [
    {
      title: "Couple Story Generator",
      description: "Let Heart Spark write a short, fun romantic story starring you and your crush.",
      icon: <BookOpen className="w-6 h-6 text-pink-500" />,
      path: "/tools/story",
      color: "bg-pink-100 dark:bg-pink-900/30",
      badge: "New"
    },
    {
      title: "Crush Prediction",
      description: "Enter details to get a funny prediction and probability score.",
      icon: <Sparkles className="w-6 h-6 text-rose-500" />,
      path: "/tools/prediction",
      color: "bg-rose-100 dark:bg-rose-900/30",
      badge: undefined
    },
    {
      title: "Funny Love Titles",
      description: "Generate random titles like 'Certified Heart Thief'.",
      icon: <Wand2 className="w-6 h-6 text-fuchsia-500" />,
      path: "/tools/titles",
      color: "bg-fuchsia-100 dark:bg-fuchsia-900/30",
      badge: undefined
    },
    {
      title: "Daily Love Fortune",
      description: "Get your random daily fortune.",
      icon: <Flame className="w-6 h-6 text-purple-500" />,
      path: "/tools/fortune",
      color: "bg-purple-100 dark:bg-purple-900/30",
      badge: undefined
    },
    {
      title: "Quick AI Advice",
      description: "Get cute, playful advice generated by Heart Spark.",
      icon: <MessageSquareHeart className="w-6 h-6 text-rose-500" />,
      path: "/tools/ai-advice",
      color: "bg-rose-100 dark:bg-rose-900/30",
      badge: undefined
    },
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      <div className="text-center space-y-6 flex flex-col items-center">
        <Logo size="lg" />
        <div className="space-y-2">
          <h1 className="text-4xl md:text-5xl font-black tracking-tight text-slate-900 dark:text-white">
            Relationship <span className="text-transparent bg-clip-text bg-gradient-to-r from-pink-500 to-purple-500">Toolkit</span>
          </h1>
          <p className="text-lg text-zinc-500 dark:text-zinc-400 font-medium max-w-2xl mx-auto">
            Explore our collection of fun, AI-powered relationship tools designed to decode your heart's deepest mysteries.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {tools.map((tool, index) => (
          <motion.div
            key={tool.title}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 * index }}
          >
            <Link to={tool.path} className="block h-full relative group">
              <Card className="h-full flex flex-col p-6 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl border-pink-100 dark:border-pink-900/30 hover:border-pink-300 dark:hover:border-pink-700 transition-all duration-300 relative overflow-hidden hover:shadow-[0_0_20px_rgba(236,72,153,0.2)] hover:-translate-y-1 rounded-2xl">
                {tool.badge && (
                  <div className="absolute top-4 right-4 bg-gradient-to-r from-pink-500 to-purple-500 text-white text-[10px] uppercase tracking-wider font-bold px-3 py-1 rounded-full shadow-sm">
                    {tool.badge}
                  </div>
                )}
                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center mb-4 transition-transform duration-300 group-hover:scale-110 group-hover:rotate-3 ${tool.color}`}>
                  {tool.icon}
                </div>
                <h3 className="text-xl font-bold text-zinc-900 dark:text-white mb-2 group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-pink-500 group-hover:to-purple-500 transition-all">
                  {tool.title}
                </h3>
                <p className="text-zinc-600 dark:text-zinc-400 flex-grow text-sm">
                  {tool.description}
                </p>
              </Card>
            </Link>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
