import { motion } from 'motion/react';
import { Card } from '../components/Card';
import { Link } from 'react-router-dom';
import { Star, Wand2, BookOpen, Flame, MessageSquareHeart, Brain, Bot } from 'lucide-react';

export function Tools() {
  const tools = [
    {
      title: "LoveGPT",
      description: "Talk to your personal AI relationship coach. Ask advice, send screenshots, and get help.",
      icon: <Bot className="w-6 h-6 text-indigo-500" />,
      path: "/love-gpt",
      color: "bg-indigo-100 dark:bg-indigo-900/30",
      badge: "New"
    },
    {
      title: "Text Analyzer",
      description: "Confused by their text? Let AI decode what they really mean.",
      icon: <Brain className="w-6 h-6 text-indigo-500" />,
      path: "/analyzer",
      color: "bg-indigo-100 dark:bg-indigo-900/30",
    },
    {
      title: "Crush Prediction",
      description: "Enter details to get a funny prediction and probability score.",
      icon: <Star className="w-6 h-6 text-indigo-500" />,
      path: "/tools/prediction",
      color: "bg-indigo-100 dark:bg-indigo-900/30",
    },
    {
      title: "Funny Love Titles",
      description: "Generate random titles like 'Certified Heart Thief'.",
      icon: <Wand2 className="w-6 h-6 text-indigo-500" />,
      path: "/tools/titles",
      color: "bg-indigo-100 dark:bg-indigo-900/30",
    },
    {
      title: "Couple Story Generator",
      description: "Generate a short romantic story using your names.",
      icon: <BookOpen className="w-6 h-6 text-indigo-500" />,
      path: "/tools/story",
      color: "bg-indigo-100 dark:bg-indigo-900/30",
    },
    {
      title: "Daily Love Fortune",
      description: "Get your random daily fortune.",
      icon: <Flame className="w-6 h-6 text-indigo-500" />,
      path: "/tools/fortune",
      color: "bg-indigo-100 dark:bg-indigo-900/30",
    },
    {
      title: "AI Love Advice",
      description: "Get cute, playful advice generated by AI.",
      icon: <MessageSquareHeart className="w-6 h-6 text-indigo-500" />,
      path: "/tools/ai-advice",
      color: "bg-indigo-100 dark:bg-indigo-900/30",
    },
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white">
          More Tools
        </h1>
        <p className="text-lg text-slate-600 dark:text-slate-400">
          Explore more fun generators and predictions.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {tools.map((tool, index) => (
          <motion.div
            key={tool.title}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 * index }}
          >
            <Link to={tool.path} className="block h-full relative">
              <Card className="h-full flex flex-col hover:border-indigo-300 dark:hover:border-indigo-700 transition-colors relative overflow-hidden">
                {tool.badge && (
                  <div className="absolute top-4 right-4 bg-zinc-900 text-white dark:bg-white dark:text-zinc-900 text-xs font-bold px-3 py-1 rounded-full shadow-sm">
                    {tool.badge}
                  </div>
                )}
                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center mb-4 ${tool.color}`}>
                  {tool.icon}
                </div>
                <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">
                  {tool.title}
                </h3>
                <p className="text-slate-600 dark:text-slate-400 flex-grow">
                  {tool.description}
                </p>
              </Card>
            </Link>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
